# This is a basic workflow to help you get started with Actions

name: getting started

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world
      - name: lpg th pebulid disc space
        run:df
      - name:checkout the git hub branch
        run:actions/checkout@v2
      - name:setup jdk 1.8
        run:actions/setup-java@v1
        with:
        java-version: 1.8
      - name:build your jakrta app with maven
        run:echo mvn -B package ..file pom.xml
    

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Hai Anirudh
          echo what is in the diectory
          ls -a
          echo
          echo 1.is java installed
          java -version
          echo
          echo 2.is git hub installed?
          git --version
          echo 3.what about bulid tools?
          echo anirudh
          mvn --version
          gradle --version
          ant -version
          echo
          echo 4.where is the Android SDK Root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 5.Where are the selenium jars?
          echo $SELENIUM_JAR_PATH
          echo
          echo 6.where is the workspace location?
          echo SRUNNER_WORKSPACE
          echo
          echo 7.who is unning this script
          whoami
          echo 8.how is the disc laid out?
          df
          echo 9.what environment vaiables are available?
          env
          echo
          echo aniudh is done with second video
